## Numpy

In [14]:
# Numpy
import numpy as np

In [15]:
a = np.array([])
type(a)

numpy.ndarray

In [16]:
one_d_array = np.array([1, 2, 3, 4, 5])
one_d_array

array([1, 2, 3, 4, 5])

In [17]:
one_d_array.ndim # ndim attributes shows the number of dimension of an array

1

In [18]:
# size attributes returns the size/length of the array
one_d_array.size

5

In [19]:
np.zeros(5) # by default it produce float

array([0., 0., 0., 0., 0.])

In [20]:
# zeros() method takes another parameter for data type
np.zeros(5, dtype=int) # array of int

array([0, 0, 0, 0, 0])

In [21]:
# first parameter denotes the starting point
# second paramter denotes the ending point
# if the third parameter was not specified then 1 is used as default
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [22]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [23]:
# reshaping an array
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# flatten an array
two_d_arr = np.arange(10).reshape(2, 5)
print(two_d_arr)
two_d_arr.ravel() 

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# transpose of an array
np.arange(10).reshape(2, 5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr.max(), arr.min() # finding max, min

(9, 0)

In [30]:
np.exp(arr) # finding exponetial 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [31]:
np.sqrt(arr) # finding square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
arr[5] # accessing the 6th element by index

5

In [33]:
for element in arr:
    print(element, end="\t")

0	1	2	3	4	5	6	7	8	9	

# Linear Algebra

In [34]:
_2d_arr = np.array([[10, 20], [30, 40]])
_2d_arr

array([[10, 20],
       [30, 40]])

In [35]:
_2d_arr.transpose() # transpose

array([[10, 30],
       [20, 40]])

In [36]:
%%time
np.linalg.inv(_2d_arr) # inverse

CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 57.6 ms


array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [37]:
identity = np.eye(3, dtype=int) # 3x3 Identity matrix
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
_2d_arr @ _2d_arr # matrix product

array([[ 700, 1000],
       [1500, 2200]])

In [39]:
np.trace(_2d_arr)  # trace

50