# Principal Component Analysis(PCA)

In [1]:
import numpy as np # import numpy

In [29]:
# sample dataset
X = np.array([[1,2],[3,4],[5,6]])
m, n = X.shape
print(X)
print(m, end=',')
print(n)

[[1 2]
 [3 4]
 [5 6]]
3,2


In [30]:
# calculate the mean of each column
M = np.mean(X, axis=0)
M

array([3., 4.])

In [31]:
# center columns by subtracting column means
X = X - M
X

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [32]:
# mean and standard deviation of centered matrix
print(np.mean(X))
print(np.std(X))

0.0
1.632993161855452


In [72]:
# calculate covariance matrix of centered matrix
Y = np.cov(X.T) # Y = (X.T @ X)/n
Y

array([[4., 4.],
       [4., 4.]])

In [73]:
# SVD of the covariance matrix, Y
u, s, vh = np.linalg.svd(Y) # Y = USV'
print(u)
print(s)
print(vh)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [83]:
# project the original data
PC = vh.dot(X.T) # PC = V.X'=> PC = V' dot X'
PC # principal components

array([[ 2.82842712e+00,  0.00000000e+00, -2.82842712e+00],
       [-2.22044605e-16,  0.00000000e+00,  2.22044605e-16]])