In [1]:
!pip install scikit-learn

     |████████████████████████████████| 6.8 MB 4.2 MB/s eta 0:00:01
     |████████████████████████████████| 25.7 MB 4.9 MB/s eta 0:00:01


# Sci-kit Learn

In [2]:
# Firstly we need to import necessary libraries
import numpy as np
import pandas as pd

# Supervised Classification Learning Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, auc, roc_curve

In [3]:
dataset = pd.read_csv(r"../../Top-5-Machine-Learning-Libraries-in-Python-master/dataset/student_result.csv")
dataset.head()

math  bangla  english  result
0    70      80       90       1
1    30      40       50       0
2    50      20       35       0
3    80      33       33       1
4    33      35       36       1

In [4]:
X = dataset.drop("result", axis=1)
y = dataset["result"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [5]:
clf_lr = LogisticRegression()
pred_lr = clf_lr.fit(X_train, y_train).predict(X_test)

clf_knn = KNeighborsClassifier()
pred_knn = clf_knn.fit(X_train, y_train).predict(X_test)

clf_rf = RandomForestClassifier(random_state=1)
pred_rf = clf_rf.fit(X_train, y_train).predict(X_test)

clf_dt = DecisionTreeClassifier()
pred_dt = clf_dt.fit(X_train, y_train).predict(X_test)

In [6]:
print("Accuracy of Logistic Regression:", accuracy_score(pred_lr, y_test))
print("Accuracy of KNN:", accuracy_score(pred_knn, y_test))
print("Accuracy of Random Forest:", accuracy_score(pred_rf, y_test))
print("Accuracy of Decision Tree:", accuracy_score(pred_dt, y_test))

Accuracy of Logistic Regression: 0.6
Accuracy of KNN: 0.6
Accuracy of Random Forest: 0.8
Accuracy of Decision Tree: 0.8


In [7]:
print(classification_report(pred_lr, y_test))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.67      0.67      0.67         3

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5



In [8]:
print(classification_report(pred_rf, y_test))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.67      1.00      0.80         2

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5



In [9]:
print(classification_report(pred_knn, y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.60      0.75         5

    accuracy                           0.60         5
   macro avg       0.50      0.30      0.37         5
weighted avg       1.00      0.60      0.75         5



/home/shehyaaz/Documents/Data-Science-Future-Skills/programs/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
print(classification_report(pred_dt, y_test))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5



In [11]:
print(confusion_matrix(pred_lr, y_test))

[[1 1]
 [1 2]]


In [12]:
print(confusion_matrix(pred_rf, y_test))

[[2 1]
 [0 2]]


In [13]:
print(confusion_matrix(pred_dt, y_test))

[[1 0]
 [1 3]]


In [14]:
print(confusion_matrix(pred_knn, y_test))

[[0 0]
 [2 3]]
